# Generated by Django 4.1.2 on 2022-10-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_results_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fairings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reused', models.BooleanField(blank=True, null=True)),
                ('recovery_attempt', models.BooleanField(blank=True, null=True)),
                ('recovered', models.BooleanField(blank=True, null=True)),
                ('ships', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Fairings',
            },
        ),
    ]
