# Generated by Django 4.1.2 on 2022-10-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_links_patch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flickr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_ships', models.CharField(blank=True, max_length=255, null=True)),
                ('original', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reddit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.URLField(blank=True, max_length=500, null=True)),
                ('launch', models.URLField(blank=True, max_length=500, null=True)),
                ('media', models.URLField(blank=True, max_length=500, null=True)),
                ('recovery', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='patch',
            name='small',
        ),
        migrations.AddField(
            model_name='links',
            name='article',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='links',
            name='presskit',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='links',
            name='webcast',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='links',
            name='wikipedia',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='links',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patch',
            name='campaign',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patch',
            name='large',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
