# Generated by Django 4.1.2 on 2022-10-10 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_results_created_remove_results_updated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='links',
            options={'verbose_name_plural': 'Links'},
        ),
        migrations.RemoveField(
            model_name='spacex',
            name='created',
        ),
        migrations.RemoveField(
            model_name='spacex',
            name='updated',
        ),
    ]
