# Generated by Django 4.1.2 on 2022-10-10 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_results_iid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patch',
            old_name='campaign',
            new_name='small',
        ),
    ]
