# Generated by Django 4.1.2 on 2022-10-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_campaign_patch_small'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fairings',
            name='ships',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flickr',
            name='small_ships',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='capsules_ships',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='crew_ships',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='failures_ships',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='payloads_ships',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='ships_ships',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
