# Generated by Django 4.1.2 on 2022-10-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_links_s'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='links',
            options={},
        ),
        migrations.RenameField(
            model_name='flickr',
            old_name='small_ships',
            new_name='small',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='capsules_ships',
            new_name='capsules',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='crew_ships',
            new_name='crew',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='failures_ships',
            new_name='failures',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='payloads_ships',
            new_name='payloads',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='ships_ships',
            new_name='ships',
        ),
        migrations.RemoveField(
            model_name='links',
            name='s',
        ),
        migrations.AddField(
            model_name='results',
            name='fairings',
            field=models.ManyToManyField(blank=True, null=True, to='api.fairings'),
        ),
    ]
