# Generated by Django 4.1.2 on 2022-10-11 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_links_flickr_links_patch_links_reddit_results_links_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='links',
            options={'verbose_name_plural': 'Links'},
        ),
    ]
