# Generated by Django 4.1.2 on 2022-10-12 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_result_launches_alter_launches_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='flickr',
        ),
        migrations.RemoveField(
            model_name='links',
            name='patch',
        ),
        migrations.RemoveField(
            model_name='links',
            name='reddit',
        ),
        migrations.AddField(
            model_name='links',
            name='flickr',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.flickr'),
        ),
        migrations.AddField(
            model_name='links',
            name='patch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.patch'),
        ),
        migrations.AddField(
            model_name='links',
            name='reddit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.reddit'),
        ),
    ]
