# Generated by Django 4.1.2 on 2022-10-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_links_flickr_remove_links_patch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fairings',
            name='ships',
            field=models.JSONField(default=list),
        ),
    ]
