# Generated by Django 4.1.2 on 2022-10-12 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_flickr_original_alter_flickr_small_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='flickr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.flickr'),
        ),
        migrations.AlterField(
            model_name='links',
            name='patch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.patch'),
        ),
        migrations.AlterField(
            model_name='links',
            name='reddit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.reddit'),
        ),
        migrations.AlterField(
            model_name='results',
            name='fairings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fairings'),
        ),
        migrations.AlterField(
            model_name='results',
            name='links',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.links'),
        ),
    ]
