# Generated by Django 4.1.2 on 2022-10-12 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_links_flickr_alter_links_patch_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Launches',
        ),
    ]
