# Generated by Django 4.1.2 on 2022-10-13 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_cores_remove_results_cores_results_cores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cores',
            options={'verbose_name_plural': 'Cores'},
        ),
    ]
