# Generated by Django 4.1.2 on 2022-10-13 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_remove_results_cores_results_cores'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cores',
        ),
    ]
